### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/JuliaDynamics#2]
I am not sure which parts of the README are true and which are not, since I am not sure how the website works...

For example, I think the first part of the readme is not true anymore, this website is not built out of many other repositories. All relevant information for the website is contained here in this repo. 

@jaredhowland could you please delete information in the README that is outdated? My goal is to be able to handle this repo without your help, but unfortunately some babysteps need to be taken first...

Another example: In the software requirements, I don't think Documenter is actually used in this website either, correct?

**Comment by Datseris** [comment]
Ah I can see there is a `makeall.jl` file that builds benchmarks and other stuff . But we don't really need it I think. Perhaps I want to keep:

```
println("========================================")
println("Building examples")
cd("../$dir_examples")
run(`julia make.jl`)
```

**Comment by jaredhowland** [comment]
I'm not sure how you wanted your project set up. Nor am I super familiar with Julia and Jupyter (just a hobby programmer who works in an academic library with exposure to lots of different fields 😄 ). So I left the README alone assuming you would have some better idea of what parts you would want to use and what parts you wouldn't. Here's my best guess but you will ultimately have to decide how you want things to work:

```
# JuliaDynamics.jl website

In this repository the following additional resources are defined:
* A common header used in every single page.
* A common navigation menu (on the top of each page).
* A common footer.
* The main page.
* **JuliaDynamics.jl** code snippets which are shown in the main page.
* Citation page.

[Jekyll](https://jekyllrb.com) is used to generate the (static) website from all different parts.

The website itself uses the following technologies:

JavaScript libraries:
* **jquery.js**
* **Require.js**
* **Bootstrap.js** for the layout.
* **MathJax.js** for representing latex formulas.
* **highlight.js** to dynamically highlight the source code.
* **Chart.js** for the interactive benchmark plots.

CSS:
* **Bootstrap.css**
* **font-awesome**
* **Lato|Ubuntu+Mono**

A basic principle is that any code that is shown should be run and tested automatically before it is included.

## Software Requirements

* [Jekyll](https://jekyllrb.com)

## Build process

The complete build process of all resources and the website itself can be done with `julia makeall.jl`.

This script runs the following operations that can of course also be performed manually to obtain finer control over the build process:

* Copy results of benchmarks into `src/benchmark-data` and their source code into `src/_benchmarks_sourcecode`.
* Run code snippets (which then are shown in the main page) with `julia make.jl` in `src/_codesnippets`.

Finally, one uses jekyll to build website:
    * For development run jekyll interactively: `jekyll serve`
    * To just create it once: `jekyll build`
This will create the finished website in the `build` directory which then can be deployed to the server.
````
