### ISSUE TITLE
Where to put Code snippets and their videos?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/JuliaDynamics#3]
@jaredhowland I can see from here: https://github.com/JuliaDynamics/JuliaDynamics/blob/master/src/_codesnippets/make.jl that in the original QuantumOptics the code examples where done automatically. This is not necessary here, we don't have to run Julia.

But could you please tell me where in the source code do I have to paste the code part, and how can I link in videos instead of just images? In the index.html I see:

```
        <div class="row">
            <div class="col-lg-12">
                <div class="tab-content">
                    {% include codesnippet.html id="example1" name="test" imgname="test.svg" title="Particle in Harmonic Trap"%}
                    {% include codesnippet.html id="example2" name="test" imgname="test.svg" title="Squeezed Fock State" %}
                    {% include codesnippet.html id="example3" name="test" imgname="test.svg" title="Spin-3/2-System" %}
                    {% include codesnippet.html id="example4" name="test" imgname="test.svg" title="Three-Level System" %}
                    {% include codesnippet.html id="example5" name="test" imgname="test.svg" title="Jaynes-Cummings System" %}
                </div>
            </div>
</div>
```
but from this I can't really deduce how to proceed...

**Comment by jaredhowland** [comment]
This pulls in code from the `src/_codesnippets/build` directory. So build your code examples and put them in that directory.

In the code snippet you included, change the `id` to whatever you'd like but it is probably easiest to stick with the numbering convention.

The `name="test"` section should be changed. `test` should be the name of whatever the `*.jl` name was in the `src/_codesnippets/build` directory mentioned above. So if the code in `src/_codesnippets/build` was `billiards.jl` then it should be `name="billiards"`. While you're at it change the `title` variable to match the example code and image/video.

The `imgname="test.svg"` pulls images from the `./images/codesnippets` directory. You can replace `test.svg` with any image you want that's in that directory. Just give it an unique name. If you want videos instead, you will want to tweak the `includes/codesnippet.html` template with an if/then statement replacing line 11. Something like this should work (haven't tested):

```
{% if include.imgname %}
    <img class="img-responsive" src="./images/codesnippets/{{ include.imgname }}" alt="">
{% elsif include.vidname %}
    <video width="320" height="240" controls>
        <source src="./images/codesnippets/{{ include.vidname }}" type="{{ include.vidtype }}">
        Your browser does not support the video tag.
    </video>
{% endif %}
```

The example code you provided would change as follows for videos:

```
{% include codesnippet.html id="example1" name="test" vidname="movie.mp4" vidtype="video/mp4" title="Example" %}
```

Or if you have another preferred way of embedding videos (embedded YouTube clips, etc), change the if/then statement above to match the required embed code. See <https://www.w3schools.com/html/html5_video.asp> or <https://davidwalsh.name/html5-video> for other ways to embed videos.

You can just place the video files, if you're hosting them yourself, in the same images folder as the other code snippet images. Or change my example code from:

```
<source src="./images/codesnippets/{{ include.vidname }}" type="{{ include.vidtype }}">
```

to 

```
<source src="./videos/codesnippets/{{ include.vidname }}" type="{{ include.vidtype }}">
```

and create a `./videos/codesnippets/` directory to store videos in.

Does this help?

**Comment by Datseris** [comment]
Thanks so much, this is very detailed and I will put it to the test as soon as possible (probably next weekend where I have some free time off work).  I really appreciate your help, especially since you said you are not a Julia user!

**Comment by Datseris** [comment]
Oh my god Jared I am absolutely ecstatic right now. Not only I have managed to change the code snippets to actually include my code examples, **but I have also managed to make em show videos** using your code.

OMGGGGGGGGGGGGGGGGGGGGGGG!!!!!

Just check it out this is amazing: https://juliadynamics.github.io/JuliaDynamics/

**Comment by jaredhowland** [comment]
That's looking awesome! Congrats!
