### ISSUE TITLE
Link to "getting started"

### ISSUE THREAD

**Issue by GMGassner** [JuliaDynamics/JuliaDynamics#33]
Hi all,
it's only a tiny observation I stumbled uppon. The link to "Getting Started" returns a 404 because the url scheme changed.
[Julia's setup instructions](https://docs.julialang.org/en/stable/manual/getting-started/) shoud refer to [new Getting Started](https://docs.julialang.org/en/v1/manual/getting-started/) aka https://docs.julialang.org/en/v1/manual/getting-started/ .
Thanks for you incredible work!

best,
GMGassner

**Comment by Datseris** [comment]
Thank you very much for your kind words!
