### ISSUE TITLE
Estimate correlation dimension

### ISSUE THREAD

**Issue by qubit0** [JuliaDynamics/JuliaDynamics#43]
I got the following code from : https://juliadynamics.github.io/JuliaDynamics/

```
using DynamicalSystems, PyPlot

ds = Systems.roessler()
tr = trajectory(ds, 1000.0; dt = 0.05)

τ = estimate_delay(tr[:, 1], "mi_min") # first minimum of mutual information

figure(figsize = (10, 6)); subplot(1,2,1)
for method in ["afnn", "fnn", "f1nn"]
    Ds = estimate_dimension(tr[:, 1], τ, 1:6, method)
    plot(1:6, Ds ./ maximum(Ds), label = method, marker = "o")
end
legend(); xlabel("\$\\gamma\$ (temporal neighbors)")

subplot(1,2,2, projection = "3d")
rec = embed(tr[:, 1], 4, τ)
plot3D(rec[1:2000, 1],rec[1:2000, 2],rec[1:2000, 3])
```

The `estimate_dimension` function does not work. What is the correct way to do in version 2.3.2?

I tried this:
```
ds = Systems.roessler()
tr = trajectory(ds, 1000.0; dt = 0.05)

τ = estimate_delay(tr[:, 1], "mi_min") # first minimum of mutual information
grassberger_dim(tr[:, 1], estimate_boxsizes(tr[:, 1]), τ)
```
But I got `ERROR: MethodError: no method matching estimate_boxsizes(::Vector{Float64})` . Isn't `estimate_boxsizes` supposed to take just the dataset?

**Comment by Datseris** [comment]
https://juliadynamics.github.io/DynamicalSystems.jl/dev/embedding/traditional/#DelayEmbeddings.optimal_traditional_de is the function you need. I have to update the website, thanks for letting me know!

**Comment by qubit0** [comment]
Thanks a lot for replying!
Is the estimator here a correlation dimension? Why does it asymptotically reaches 1?

This is not similar to GP algorithm ( https://github.com/notsebastiano/GP_algorithm)  right? 

Is there an implementation of GP algorithm in Dynamical systems to calculate the correlation dimension?

For stochastic data `dataran=randn(20000)*0.1`, the correlation dimension should linearly increase with the embedding dimension(https://www.nature.com/articles/nature14318). However, the dimension estimated by  `optimal_traditional_de` asymptotically reaches 1.

Sorry if my questions are too basic. I am new to the field as well as the Julia ecosystem.

**Comment by Datseris** [comment]
I think you are talking about something else... the code you pasted originally estimates an optimal embedding dimension for a timeseries. This isn't really related to the fractal dimension, at least not from the perspective of the algorithm. If you want to compute a fractal dimension you need https://juliadynamics.github.io/FractalDimensions.jl/dev/  which also has the correlation sum
